# PYTHON_ARGCOMPLETE_OK
# This script is generated by AI
"""radio-hil - minimal client for the radio-hil Pis (runs on your laptop)

Examples:
    radio-hil fetch
    radio-hil list
    radio-hil flash -b nrf52840dk-1 nrf52840dk-2 -f app.elf
    radio-hil build-flash -b nrf52840dk-2 frdm-kw41z-1 -f examples/basic/hello-world
    radio-hil term nrf52840dk-1
    radio-hil reset -b nrf52840dk-1        (or -a for all, -u for all in use)
    radio-hil poweroff -a                  (or -b <names>, -u)
    radio-hil poweron -b frdm-kw41z-1
    radio-hil poweroff -p radio-hil-2      (all boards of a Pi, or -p 2)

Board names are <RIOT board>-<n>, where n is the trailing number of the
Pi's host name (radio-hil-1 -> 1, radio-hil-2 -> 2). Hosts without a
trailing number get their position in the host list instead. Each Pi has
every board type at most once.

The Pis are reached as ssh hosts radio-hil-1, radio-hil-2 (set them up in
~/.ssh/config), or set RADIO_HIL_HOSTS="host1 host2 ...".
power/reset need radio-hil-power installed on the Pis.
flash, build-flash, poweron, poweroff and reset work on all given boards at the same time.

Note: build-flash builds with your local RIOT checkout, but flashing and
the terminal go through the RIOT checkout on the Pis (PI_APP). Keep both
roughly in sync, otherwise flasher configs or programmer flags may differ
and flashing fails in confusing ways.
"""

import argparse
import functools
import getpass
import json
import os
import re
import shlex
import subprocess
import sys
import threading
from concurrent.futures import ThreadPoolExecutor

try:
    import argcomplete
    from argcomplete.completers import DirectoriesCompleter, FilesCompleter
except ImportError:          # completion is optional, the CLI works without it
    argcomplete = None

HOSTS = os.environ.get("RADIO_HIL_HOSTS", "radio-hil-1 radio-hil-2").split()
CACHE = os.path.expanduser("~/.cache/radio-hil/boards.json")
# Give up quickly on Pis that are switched off or unreachable
SSH_OPTS = ["-o", "ConnectTimeout=3"]
# Any RIOT application on the Pis, only used as make context for flash/term
PI_APP = "/srv/radio-hil/RIOT/examples/basic/hello-world"


def die(msg):
    print(f"radio-hil: {msg}", file=sys.stderr)
    sys.exit(1)


PRINT_LOCK = threading.Lock()


def warn(msg):
    with PRINT_LOCK:
        print(f"radio-hil: {msg}", file=sys.stderr, flush=True)


def out(text, prefix=""):
    """Print text, every line with prefix; safe to call from several threads."""
    with PRINT_LOCK:
        for line in text.splitlines():
            print(f"{prefix}{line}", flush=True)


def parallel(func, items):
    """Run func(item) for all items at the same time, return the results in order."""
    items = list(items)
    if len(items) <= 1:
        return [func(item) for item in items]
    with ThreadPoolExecutor(max_workers=len(items)) as pool:
        return list(pool.map(func, items))


def ssh(host, cmd, tty=False, capture=False):
    args = ["ssh", *SSH_OPTS] + (["-t"] if tty else []) + [host, cmd]
    return subprocess.run(args, text=True, capture_output=capture)


def ssh_stream(host, cmd, prefix=""):
    """Run cmd on host, print its output line by line (with prefix), return all of it."""
    proc = subprocess.Popen(["ssh", *SSH_OPTS, host, cmd], stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True)
    lines = []
    for line in proc.stdout:
        out(line, prefix)
        lines.append(line)
    proc.wait()
    return "".join(lines)


@functools.lru_cache(maxsize=None)
def load_boards():
    try:
        with open(CACHE) as fh:
            return json.load(fh)
    except FileNotFoundError:
        die("no board list yet, run 'radio-hil fetch' first")


def entry(name):
    boards = load_boards()
    if name not in boards:
        die(f"unknown board '{name}' (known: {', '.join(sorted(boards))})")
    if not isinstance(boards[name], dict) or "host" not in boards[name]:
        die("board list is outdated, run 'radio-hil fetch' again")
    return boards[name]


def group_by_host(names):
    """{host: [(name, uid), ...]} for the given board names."""
    groups = {}
    for name in names:
        e = entry(name)
        groups.setdefault(e["host"], []).append((name, e["uid"]))
    return groups


# --- fetch / list -----------------------------------------------------------

def host_number(host, position):
    """Trailing number of the host name (radio-hil-2 -> 2), else position."""
    m = re.search(r"-(\d+)$", host)
    return int(m.group(1)) if m else position


def cmd_fetch():
    boards = {}
    numbers = {}
    for position, host in enumerate(HOSTS, start=1):
        idx = host_number(host, position)
        if idx in numbers:
            die(f"{host} and {numbers[idx]} both map to number {idx}, "
                f"rename one of them in RADIO_HIL_HOSTS")
        numbers[idx] = host
        res = ssh(host, "cat ${NM_CONFIG_DIR:-/etc/inet-nm}/nodes.json", capture=True)
        if res.returncode != 0:
            warn(f"{host} not reachable, skipped ({res.stderr.strip()})")
            continue
        for n in json.loads(res.stdout):
            if n.get("ignore"):
                continue
            name = f"{n['board']}-{idx}"
            if name in boards:
                warn(f"{host} has {n['board']} more than once, skipped {n['uid']}")
                continue
            boards[name] = {"uid": n["uid"], "board": n["board"], "host": host}
    if not boards:
        die("no boards fetched")
    os.makedirs(os.path.dirname(CACHE), exist_ok=True)
    with open(CACHE, "w") as fh:
        json.dump(boards, fh, indent=2, sort_keys=True)
    load_boards.cache_clear()
    cmd_list()


def complete_boards(prefix, parsed_args, **_):
    """Tab completion: board names from the cache, without the ones already given."""
    try:
        with open(CACHE) as fh:
            boards = json.load(fh)
    except (OSError, ValueError):
        return []
    given = getattr(parsed_args, "boards", None) or []
    return [name for name in sorted(boards) if name.startswith(prefix) and name not in given]


def complete_pis(prefix, parsed_args, **_):
    """Tab completion: Pi host names, without the ones already given."""
    given = getattr(parsed_args, "pis", None) or []
    return [h for h in HOSTS if h.startswith(prefix) and h not in given]


def resolve_pi(pi):
    """Host for a Pi given as host name (radio-hil-2) or number (2)."""
    if pi in HOSTS:
        return pi
    for position, host in enumerate(HOSTS, start=1):
        if pi.isdigit() and host_number(host, position) == int(pi):
            return host
    die(f"unknown Pi '{pi}' (known: {', '.join(HOSTS)})")


def completer(arg, func):
    """Attach a tab completer to an argparse argument (no-op without argcomplete)."""
    if argcomplete:
        arg.completer = func


def cmd_list():
    """Board names, grouped by the Pi they are connected to."""
    by_host = {}
    for name, e in load_boards().items():
        by_host.setdefault(e.get("host", "?") if isinstance(e, dict) else "?", []).append(name)
    order = [h for h in HOSTS if h in by_host] + sorted(set(by_host) - set(HOSTS))
    for i, host in enumerate(order):
        names = sorted(by_host[host])
        print(("\n" if i else "") + f"{host} ({len(names)} board{'s' if len(names) != 1 else ''}):")
        for name in names:
            print(f"  {name}")


# --- flash / build-flash ----------------------------------------------------

def flash(name, firmware, prefix=""):
    """Copy firmware to the board's Pi and flash it, returns True on success."""
    e = entry(name)
    host, uid = e["host"], e["uid"]
    remote = f"/tmp/{getpass.getuser()}-{name}{os.path.splitext(firmware)[1]}"
    if subprocess.run(["scp", *SSH_OPTS, "-q", firmware, f"{host}:{remote}"]).returncode != 0:
        warn(f"copying the firmware to {host} failed")
        return False
    make = (f"make -C {PI_APP} BOARD=$NM_BOARD DEBUG_ADAPTER_ID=$NM_SERIAL PORT=$NM_PORT "
            f"FLASHFILE={remote} flash-only")
    # remove the copied firmware afterwards, whatever the result
    res = ssh_stream(host, f"inet-nm-exec {shlex.quote(make)} -d {uid}; "
                           f"rm -f {shlex.quote(remote)}", prefix)
    if "RESULT:" not in res:
        warn(f"'{name}' was not flashed, it is in use by someone else or not connected")
        return False
    if not res.rstrip().endswith(": 0"):
        warn(f"flashing '{name}' failed, see output above")
        return False
    return True


def flash_all(jobs):
    """Flash {name: firmware} on all boards at the same time, returns failed names.

    With several boards every output line starts with [name]."""
    prefixed = len(jobs) > 1
    ok = parallel(lambda job: flash(job[0], job[1], f"[{job[0]}] " if prefixed else ""),
                  jobs.items())
    return [name for name, success in zip(jobs, ok) if not success]


def cmd_flash(names, firmware):
    if not os.path.isfile(firmware):
        die(f"firmware '{firmware}' not found")
    for name in names:
        entry(name)                                           # fails early on typos
    failed = flash_all({name: firmware for name in names})
    if failed:
        die(f"not flashed: {', '.join(failed)}")
    print(f"==> flashed: {', '.join(names)}")


def build(app, board):
    """Build app for board, returns the file the board's flasher needs."""
    jobs = f"-j{os.cpu_count() or 1}"
    if subprocess.run(["make", jobs, "-C", app, f"BOARD={board}"]).returncode != 0:
        die(f"build for {board} failed")
    # ask RIOT which file the flasher of this board needs (.elf, .bin, .hex)
    res = subprocess.run(["make", "-s", "--no-print-directory", "-C", app, f"BOARD={board}",
                          "info-debug-variable-FLASHFILE"], capture_output=True, text=True)
    firmware = res.stdout.strip().splitlines()[-1] if res.stdout.strip() else ""
    if res.returncode != 0 or not firmware:
        die(f"could not determine the flash file for {board}:\n{res.stderr}")
    if not os.path.isfile(firmware):
        die(f"build for {board} did not produce '{firmware}'")
    return firmware


def cmd_build_flash(names, app):
    boards = {name: entry(name)["board"] for name in names}   # fails early on typos
    firmware = {}
    for board in dict.fromkeys(boards.values()):              # build each type once
        firmware[board] = build(app, board)
    for name, board in boards.items():
        print(f"==> flashing {name} with {firmware[board]}")
    failed = flash_all({name: firmware[board] for name, board in boards.items()})
    if failed:
        die(f"not flashed: {', '.join(failed)}")
    print(f"==> flashed: {', '.join(names)}")


# --- term -------------------------------------------------------------------

def cmd_term(name):
    e = entry(name)
    make = f"make -C {PI_APP} BOARD=$NM_BOARD PORT=$NM_PORT term"
    # The Pi may not know the local terminal type (e.g. xterm-kitty) and
    # tmux refuses to start then, so always use a type every system knows.
    # Own tmux session per board (-n), otherwise a second 'term' takes over
    # the session of the first one.
    ssh(e["host"], f"TERM=xterm-256color inet-nm-tmux -n {name} -d {e['uid']} "
                   f"-x {shlex.quote(make)}", tty=True)


# --- power / reset ----------------------------------------------------------

def power(action, names, all_boards, in_use, pis=None):
    # radio-hil-power is installed on the Pis (/usr/local/bin);
    # -a (all) and -u (in use) are resolved there
    if all_boards or in_use:
        flag = "-a" if all_boards else "-u"
        jobs = {host: flag for host in HOSTS}
    elif pis:
        jobs = {resolve_pi(pi): "-a" for pi in pis}       # all boards of these Pis
    elif names:
        jobs = {host: " ".join(uid for _, uid in members)
                for host, members in group_by_host(names).items()}
    else:
        die("give boards with -b, Pis with -p, -a for all or -u for all in use")
    def run(job):
        host, arg = job
        res = ssh(host, f"radio-hil-power {action} {arg}", capture=True)
        out(res.stdout)
        if res.returncode != 0:
            warn(f"{host}: power {action} failed: {res.stderr.strip()}")
        return res.returncode == 0

    # all Pis at the same time; on one Pi radio-hil-power switches its
    # boards together anyway
    if not all(parallel(run, jobs.items())):
        sys.exit(1)


# --- main -------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        prog="radio-hil", description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("fetch", help="get the boards of all Pis")
    sub.add_parser("list", help="show the fetched boards")

    p = sub.add_parser("flash", help="copy a firmware file to the Pi and flash it")
    completer(p.add_argument("-b", "--boards", nargs="+", required=True, metavar="NAME"),
              complete_boards)
    arg = p.add_argument("-f", "--file", required=True, help="firmware file (.elf/.bin/.hex)")
    if argcomplete:
        completer(arg, FilesCompleter(allowednames=("elf", "bin", "hex")))

    p = sub.add_parser("build-flash", help="build an application and flash it")
    completer(p.add_argument("-b", "--boards", nargs="+", required=True, metavar="NAME"),
              complete_boards)
    arg = p.add_argument("-f", "--folder", required=True, help="RIOT application folder")
    if argcomplete:
        completer(arg, DirectoriesCompleter())

    p = sub.add_parser("term", help="open the RIOT shell of a board")
    completer(p.add_argument("board", metavar="NAME"), complete_boards)

    for cmd, text in (("reset", "power cycle boards (off and on again)"),
                      ("poweron", "switch the USB power of boards on"),
                      ("poweroff", "switch the USB power of boards off")):
        p = sub.add_parser(cmd, help=text)
        g = p.add_mutually_exclusive_group(required=True)
        completer(g.add_argument("-b", "--boards", nargs="+", metavar="NAME"),
                  complete_boards)
        completer(g.add_argument("-p", "--pis", nargs="+", metavar="PI",
                                 help="all boards of these Pis (host name or number)"),
                  complete_pis)
        g.add_argument("-a", "--all", action="store_true", help="all boards")
        g.add_argument("-u", "--used", action="store_true", help="all boards in use")

    if argcomplete:
        argcomplete.autocomplete(parser)
    args = parser.parse_args()
    if args.cmd == "fetch":
        cmd_fetch()
    elif args.cmd == "list":
        cmd_list()
    elif args.cmd == "flash":
        cmd_flash(args.boards, args.file)
    elif args.cmd == "build-flash":
        cmd_build_flash(args.boards, args.folder)
    elif args.cmd == "term":
        cmd_term(args.board)
    elif args.cmd == "reset":
        power("reset", args.boards, args.all, args.used, args.pis)
    elif args.cmd == "poweron":
        power("on", args.boards, args.all, args.used, args.pis)
    elif args.cmd == "poweroff":
        power("off", args.boards, args.all, args.used, args.pis)


if __name__ == "__main__":
    main()
